default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 18092001
  host: 127.0.0.1
  port: 3306
  database: booking_tour

development:
  <<: *default
  database: booking_tour

test:
  <<: *default
  database: test_db_name

production:
  <<: *default
  database:
